import { StoryVideo } from '../components/stories/StoryVideo';
import { StoryCTA, TransformationStoryPage } from '../components/stories/TransformationStoryLayout';
import { Container } from '../components/ui/Container';
import { CoolIcon } from '../components/ui/CoolIcon';
import { dashaBaseline, dashaClips, dashaEarlyMeals, dashaMeals } from '../data/dashaStory';
import { escapeHtml } from '../lib/dom';

export function dashaStoryPage(): string {
  const earlyMeals = `<div class="case-early-meals">${dashaEarlyMeals.map(photo => `<figure><img src="${photo.src}" width="960" height="1280" loading="lazy" decoding="async" alt="${escapeHtml(photo.alt)}"><figcaption>${escapeHtml(photo.caption)}</figcaption></figure>`).join('')}</div>`;
  const hero = `<section class="case-hero" aria-labelledby="dasha-title">${Container({ content: `
    <a class="plain-link" href="/istorii-peremen/">${CoolIcon('arrow-left')}<span>Все истории</span></a>
    <div class="case-split"><div class="case-copy"><p class="home-kicker">История Даши · питание, энергия, форма</p><h1 id="dasha-title">«Шоколадка упала мне в руки. И я её не захотела».</h1><p class="case-lead">Я думала, что просто не могу жить без сладкого.</p><p>Даша изначально была стройной. Эта история — о том, как изменились её привычки, самочувствие и отношение к своему телу.</p><a class="plain-link" href="#dasha-start"><span>Как всё начиналось</span>${CoolIcon('arrow-down')}</a></div><div class="case-media">${StoryVideo({ ...dashaClips.chocolate, variant: 'light', portrait: true, compact: true })}</div></div>` })}</section>`;

  const start = `<section class="case-section" id="dasha-start" aria-labelledby="dasha-start-title">${Container({ content: `<div class="case-split case-split--reverse"><div class="case-copy"><p class="home-kicker">Привычный день</p><h2 id="dasha-start-title">Кофе, ещё кофе.<br>И что-нибудь сладкое.</h2><p>Сладкое было почти после каждого приёма пищи. Кофе сопровождал завтрак, обед и перекусы — это казалось обычным порядком вещей.</p><p>Но энергии было мало. Задачей стало разобраться в привычках и самочувствии, а не просто запретить шоколад.</p>${earlyMeals}</div><div class="case-media">${StoryVideo({ ...dashaClips.diet, variant: 'light', portrait: true, compact: true })}</div></div>` })}</section>`;

  const baseline = `<section class="case-section case-section--soft" aria-labelledby="dasha-baseline-title">${Container({ content: `<div class="section-intro"><div><p class="home-kicker">Исходная ситуация</p><h2 class="home-title" id="dasha-baseline-title">Сначала — посмотреть шире.</h2></div><p class="home-lead">Вместе с рационом и режимом учитывали результаты обследования. Ниже — три показателя из исходного бланка, без персональных данных.</p></div><dl class="lab-cards">${dashaBaseline.map(item => `<div><dt>${escapeHtml(item.name)}</dt><dd>${escapeHtml(item.value)} <small>${escapeHtml(item.unit)}</small></dd><p>${escapeHtml(item.reference)}</p></div>`).join('')}</dl><p class="case-note">Это исходные данные из материалов истории, а не сравнение «до и после лечения». Результаты анализов оценивает врач с учётом всего контекста. Они не доказывают причину тяги к сладкому и не являются рекомендацией принимать препараты или добавки.</p>` })}</section>`;

  const food = `<section class="case-section" aria-labelledby="dasha-food-title">${Container({ content: `<div class="case-split"><div class="case-copy"><p class="home-kicker">Что изменили</p><h2 id="dasha-food-title">Больше полноценной еды.<br>Меньше хаоса.</h2><p>Постепенно выстроили регулярные приёмы пищи. В рационе стало больше зелени, овощей и разнообразных продуктов.</p><ul class="case-list"><li>Обсуждали реальный рацион</li><li>Меняли привычки постепенно</li><li>Следили за самочувствием</li></ul><p>Без идеи «соберись и больше никогда не ешь сладкое».</p></div><figure class="case-food"><img src="${dashaMeals.src}" width="${dashaMeals.width}" height="${dashaMeals.height}" loading="lazy" decoding="async" alt="${escapeHtml(dashaMeals.alt)}"><figcaption>Реальные фотографии питания Даши после изменений.</figcaption></figure></div>` })}</section>`;

  const changes = `<section class="case-section case-section--soft" aria-labelledby="dasha-changes-title">${Container({ content: `<div class="case-split case-split--reverse"><div class="case-copy"><p class="home-kicker">Её словами</p><h2 id="dasha-changes-title">«Я теперь по-другому себя чувствую».</h2><p>Постепенно сладкое перестало так сильно интересовать Дашу. По её словам, изменились энергия и самочувствие — в том числе за пределами тренировок.</p><p>Здесь важен её собственный рассказ. Это опыт одного человека, а не обещание одинаковых изменений для всех.</p></div><div class="case-media">${StoryVideo({ ...dashaClips.changes, variant: 'light', portrait: true, compact: true })}</div></div>` })}</section>`;

  const training = `<section class="case-section" aria-labelledby="dasha-training-title">${Container({ content: `<div class="case-split"><div class="case-copy"><p class="home-kicker">Не только про сладкое</p><h2 id="dasha-training-title">Сильнее.<br>В своём теле.</h2><p>Целью было не уменьшить цифру на весах, а работать над силой, тонусом и формой тела. Подходящая нагрузка стала частью повседневной жизни.</p><div class="case-tags"><span>Движение</span><span>Сила</span><span>Новый ритм</span></div><p class="case-note">Фрагмент личной тренировки. Нагрузка подбирается индивидуально.</p></div><div class="case-media">${StoryVideo({ ...dashaClips.training, variant: 'light', portrait: true, compact: true })}</div></div>` })}</section>`;

  return TransformationStoryPage({ className: 'dasha-story-page', sections: [hero, start, baseline, food, changes, training, StoryCTA({ slug: 'dasha', eyebrow: 'Ваш первый шаг', title: 'Начать с понимания себя.', text: 'Если эта история откликается, можно спокойно разобраться в своём питании, привычках и самочувствии.', action: { label: 'Разобраться со своим телом', href: '/formula-tela/#request' }, note: '«Формула тела» — экспертный разбор, не медицинская диагностика.' })] });
}
